version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
  pre_build:
    commands:
      - npm ci
      - echo "VITE_API_URL=$VITE_API_URL"
      - chmod +x scripts/sync-codebuild-env.sh
      - ./scripts/sync-codebuild-env.sh
      - cat .env.production
  build:
    commands:
      - npm run build
      - grep -R "localhost:8080" dist || true
    finally:
      - echo "This is the finally block execution!"

artifacts:
  base-directory: dist
  files:
    - "**/*"
